/**
 * Created by johnfranklin on 3/26/16.
 */
//WThis was automatically generated. any code added to it was just wrapping to make it look nicer. not doing these tests as a result.
/*
describe('ReviewsIndexCtrl', function(e){
    beforeEach(module("AwesomeMovieReviewsClient"));
    var scope, httpBackend, createController;



    beforeEach(inject(function($rootScope, $httpBackend, $controller) {
        httpBackend = $httpBackend;
        scope = $rootScope.$new();

        createController = function(params) {
            return $controller('ReviewIndexCtrl', {
                '$scope': scope,
                '$routeParams': params
            });
        };
    }));
    afterEach(function() {
        httpBackend.verifyNoOutstandingExpectation();
        httpBackend.verifyNoOutstandingRequest();
    });
    it('should call get on reviews for a given movie', function() {
        var controller = createController({movie:"7"});

        httpBackend.expect('GET', '/reviews?movie=7')
            .respond({id:6, movie:"7", email:"a@a.a", rating:4, comment:"help"
            });

        // have to use $apply to trigger the $digest which will
        // take care of the HTTP request
        scope.$apply(function() {
            scope.runTest();
        });

        expect(scope.reviews).toEqual([{id:6, movie:"7", email:"a@a.a", rating:4, comment:"help"
        }]);

        httpBackend.flush();
    });
    it('should call get on all reviews', function() {
        var controller = createController({});

        httpBackend.expect('GET', '/reviews')
            .respond([{id:6, movie:"7", email:"a@a.a", rating:4, comment:"help"
            }, {id:7, movie:"8", email:"a@a.a", rating:4, comment:"help"
            }]);

        // have to use $apply to trigger the $digest which will
        // take care of the HTTP request

        expect(scope.reviews).toEqual([{id:6, movie:"7", email:"a@a.a", rating:4, comment:"help"
        }, {id:7, movie:"8", email:"a@a.a", rating:4, comment:"help"
        }]);

        httpBackend.flush();
    });

    describe("$scope.editModal",function(){
        it("launches a modal", function(){
            var $uibModal = {}
            var $scope = {}

            var controller = $controller(ReviewsIndexCtrl, {$scope: $scope, $uibModal: $uibModal})
            $scope.blank = {};

            $scope.launchEditModal($scope.blank);

            expect($scope.modalInstance).not.toEqualData(null)

        })
    })
})
describe('ReviewsEditCtrl', function(e){
    beforeEach(module("AwesomeMovieReviewsClient"));

    var $controller;

    beforeEach(inject(function(_$controller_){
        // The injector unwraps the underscores (_) from around the parameter names when matching
        $controller = _$controller_;
    }));


   //Just need to test close and dismiss, rest autogenerated by angular-scaffold.
    describe("$scope.dismiss",function(){
        bef
        it("dismisses the modal",function(){

        })

    })
    describe("$scope.save",function(){


    })
})*/