/**
 * Created by johnfranklin on 3/26/16.
 */
//Not really necessary. Code generated by angular scaffold.
//Should probably write something to generate these scripts into angular_scaffolding when I polish up the currently unmaintained gem later